#ifndef TRUNK_BILLIONWORDS_HEADERS_CONSTANTES_H_
#define TRUNK_BILLIONWORDS_HEADERS_CONSTANTES_H_

#define ERROR_AL_ABRIR_ARCHIVO -1
#define LARGO_BARRA_PUNTO 2
#define LARGO_PUNTO 1
#define TRIGRAM_EXPRESSION 3
#define BIGRAM_EXPRESSION 2
#define UNIGRAM_EXPRESSION 1
#define UNIGRAMTOTALWEIGHT_mauro 765575511
#define UNIGRAMTOTALWEIGHT 765296493
#define WHITE_SPACE ' '
#define WHITE_SPACE_STRING " "
#define NGRAMS_CLEANED "ngrams_cleaned_up65"
#define UNIGRAM_WEIGHT 0.002
#define BIGRAM_WEIGHT 0.42
#define TRIGRAM_WEIGHT 0.578
#define OUT_OF_LINE 999


#endif /* TRUNK_BILLIONWORDS_HEADERS_CONSTANTES_H_ */
