#ifndef TRUNK_BILLIONWORDS_HEADERS_CONSTANTES_H_
#define TRUNK_BILLIONWORDS_HEADERS_CONSTANTES_H_

#define ERROR_AL_ABRIR_ARCHIVO -1
#define GREP_COMMAND ""


#endif /* TRUNK_BILLIONWORDS_HEADERS_CONSTANTES_H_ */
