#ifndef TRUNK_BILLIONWORDS_HEADERS_CONSTANTES_H_
#define TRUNK_BILLIONWORDS_HEADERS_CONSTANTES_H_

#define ERROR_AL_ABRIR_ARCHIVO -1
#define LARGO_BARRA_PUNTO 2
#define LARGO_PUNTO 1


#endif /* TRUNK_BILLIONWORDS_HEADERS_CONSTANTES_H_ */
